const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.user = require("./user");
db.role = require("./role");
db.recipe = require("./recipe")
db.tag = require("./tags")
db.lead = require("./lead")
db.contact = require("./contact")
db.interaction = require("./interaction")
db.ROLES = ["user", "admin", "moderator"];
module.exports = db;